# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WFh-fADJ0g1NJSX7k4yW5gU85HgEq-pW
"""

#pip install streamlit

import streamlit as st

with st.chat_message("user"):
  st.write("Hello")